import type { CapabilityManifestInput } from "@sourceweft/capability-contracts";

export const builtinDocumentParsersCapabilityManifest: CapabilityManifestInput = {
  schemaVersion: 1,
  id: "sourceweft/document-parsers",
  kind: "document_parser",
  name: "SourceWeft Document Parsers",
  version: "0.1.0",
  entry: "./src/index.ts",
  documentParsers: [
      {
        id: "workspace-documents",
        title: "Workspace Document Parsers",
        mimeTypes: [
          "application/pdf",
          "image/avif",
          "image/png",
          "image/jpeg",
          "image/jpg",
          "image/webp",
          "image/tiff",
          "image/bmp",
          "image/gif",
          "text/plain",
          "text/markdown",
          "text/x-markdown",
          "text/html",
          "application/xhtml+xml",
          "application/xml",
          "text/xml",
          "image/svg+xml",
          "text/css",
          "text/javascript",
          "application/javascript",
          "application/typescript",
          "application/x-typescript",
          "application/yaml",
          "application/x-yaml",
          "text/yaml",
          "application/toml",
          "text/tab-separated-values",
          "text/csv",
          "application/csv",
          "application/json",
          "application/jsonl",
          "application/x-ndjson",
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          "application/msword",
          "application/epub+zip",
          "application/vnd.openxmlformats-officedocument.presentationml.presentation",
          "application/x-subrip",
          "text/srt",
          "application/srt",
          "text/x-sourceweft-web-url",
        ],
      },
  ],
};
