model_list:
  - model_name: chat-default
    litellm_params:
      model: os.environ/SYSTEM_DEFAULT_CHAT_MODEL

  - model_name: embed-default
    litellm_params:
      model: os.environ/SYSTEM_DEFAULT_EMBED_MODEL

  - model_name: rerank-default
    litellm_params:
      model: os.environ/SYSTEM_DEFAULT_RERANK_MODEL

  - model_name: video-default
    litellm_params:
      model: os.environ/SYSTEM_DEFAULT_VIDEO_MODEL

  - model_name: tts-default
    litellm_params:
      model: os.environ/SYSTEM_DEFAULT_TTS_MODEL

  - model_name: asr-default
    litellm_params:
      model: os.environ/SYSTEM_DEFAULT_ASR_MODEL
    model_info:
      mode: audio_transcription

  - model_name: "*"
    litellm_params:
      model: "*"
