import { defineConfig } from "tsup";

export default defineConfig({
  bundle: true,
  clean: true,
  dts: false,
  entry: {
    api: "src/api/main.ts",
    scheduler: "src/scheduler/main.ts",
    worker: "src/worker/main.ts",
  },
  format: ["esm"],
  minify: false,
  noExternal: [
    /^@sourceweft\/agent-tool-registry(\/.*)?$/,
    /^@sourceweft\/builtin-document-parsers(\/.*)?$/,
    /^@sourceweft\/builtin-retrieval(\/.*)?$/,
    /^@sourceweft\/builtin-tool-generate-image(\/.*)?$/,
    /^@sourceweft\/builtin-tool-generate-video-presentation(\/.*)?$/,
    /^@sourceweft\/builtin-tool-publish-artifact(\/.*)?$/,
    /^@sourceweft\/builtin-tool-web-search(\/.*)?$/,
    /^@sourceweft\/builtin-vfs(\/.*)?$/,
    /^@sourceweft\/capability-contracts(\/.*)?$/,
    /^@sourceweft\/capability-runtime(\/.*)?$/,
    /^@sourceweft\/contracts(\/.*)?$/,
    /^@sourceweft\/credits-core(\/.*)?$/,
    /^@sourceweft\/market-contracts(\/.*)?$/,
    /^@sourceweft\/market-sdk(\/.*)?$/,
    /^@sourceweft\/model-gateway(\/.*)?$/,
    /^@sourceweft\/sandbox-provider-daytona(\/.*)?$/,
  ],
  outDir: "dist",
  platform: "node",
  shims: false,
  sourcemap: true,
  splitting: false,
  target: "node20",
  treeshake: true,
});
