import type { PresentationSourceV1 } from "../domain/schemas";

export const basicProductOverviewFixture = {
  schemaVersion: "pptx-composer.v1",
  requirementAnalysis: {
    audience: "Product and go-to-market leaders evaluating SourceWeft",
    objective: "Explain the product promise and why teams should adopt it",
    primaryMessage: "SourceWeft turns scattered knowledge sources into grounded team outputs",
    constraints: ["Native editable PPTX output", "No empty slides", "Concise executive pacing"],
    successCriteria: ["Audience understands use cases", "Deck has clear next step"],
    language: "en",
  },
  contentBrief: {
    title: "SourceWeft Product Overview",
    subtitle: "A knowledge workspace for grounded outputs",
    narrativeArc: ["Problem", "Solution", "Workflow", "Next step"],
    keyPoints: [
      "Teams work across PDFs, URLs, notes, and SaaS sources",
      "Answers and artifacts stay grounded in selected sources",
      "Skills and working files give agents a repeatable workspace",
      "Self-hosting keeps model and data choices under team control",
    ],
    sourceSummary: "Product overview synthesized from SourceWeft positioning notes.",
  },
  deckStrategy: {
    deckTitle: "SourceWeft Product Overview",
    audienceTakeaway: "Adopt SourceWeft when grounded knowledge work needs repeatable outputs",
    storyBeats: ["Context", "Core capability", "Operational workflow", "Decision"],
    slideCountTarget: 4,
    pacing: "balanced",
  },
  designSystem: {
    name: "SourceWeft Editorial Blue",
    aspectRatio: "16:9",
    language: "en",
    palette: {
      background: "#F8FAFC",
      foreground: "#0F172A",
      accent: "#2563EB",
      muted: "#64748B",
      surface: "#E2E8F0",
    },
    typography: {
      family: "Inter",
      scale: "standard",
    },
    density: "balanced",
    layoutPrinciples: ["Strong title hierarchy", "One primary claim per slide", "Clear source-aware proof points"],
    brandNotes: "Use crisp editorial layouts with restrained blue accents.",
  },
  assetPlan: {
    items: [
      {
        id: "knowledge-graph-icon",
        kind: "icon",
        purpose: "Represent connected sources",
        description: "Simple node-link glyph for source grounding",
        required: false,
        altText: "Connected source nodes",
      },
    ],
    notes: "Use simple vector elements when no uploaded assets are available.",
  },
  slides: [
    {
      id: "slide-cover",
      role: "cover",
      title: "SourceWeft Product Overview",
      headline: "Turn scattered knowledge into grounded team outputs",
      body: ["Self-hosted", "Multi-model", "Built for deep knowledge work"],
      speakerNotes: "Open by naming the fragmentation problem.",
      visualIntent: "Editorial cover with large title and compact proof chips.",
      layoutSpec: {
        kind: "locked",
        name: "cover-hero-left",
        intent: "Large title block with supporting proof chips",
        requiredSlots: ["title", "headline", "proof-chips"],
        regions: [
          { id: "cover-title", slot: "title", x: 0.08, y: 0.16, width: 0.64, height: 0.18, zIndex: 1 },
          { id: "cover-headline", slot: "headline", x: 0.08, y: 0.38, width: 0.7, height: 0.18, zIndex: 1 },
          { id: "cover-chips", slot: "proof-chips", x: 0.08, y: 0.68, width: 0.76, height: 0.14, zIndex: 1 },
        ],
        balance: "left-weighted",
      },
      assetRefs: [],
    },
    {
      id: "slide-problem",
      role: "content",
      title: "Knowledge work is split across too many surfaces",
      body: ["Sources live in disconnected systems", "Outputs lose citation context", "Team workflows are hard to repeat"],
      visualIntent: "Three-column problem stack with short labels.",
      layoutSpec: {
        kind: "parametric",
        name: "three-column-stack",
        intent: "Compare three related pain points with equal emphasis",
        requiredSlots: ["title", "column-a", "column-b", "column-c"],
        regions: [
          { id: "problem-title", slot: "title", x: 0.08, y: 0.08, width: 0.84, height: 0.14, zIndex: 1 },
          { id: "problem-a", slot: "column-a", x: 0.08, y: 0.32, width: 0.25, height: 0.42, zIndex: 1 },
          { id: "problem-b", slot: "column-b", x: 0.38, y: 0.32, width: 0.25, height: 0.42, zIndex: 1 },
          { id: "problem-c", slot: "column-c", x: 0.68, y: 0.32, width: 0.25, height: 0.42, zIndex: 1 },
        ],
        balance: "grid",
      },
      assetRefs: [],
    },
    {
      id: "slide-solution",
      role: "content",
      title: "SourceWeft gives agents a grounded workspace",
      body: ["Connect sources", "Ask with citations", "Create reusable artifacts", "Extend with Skills"],
      visualIntent: "Workflow ribbon from source ingestion to artifact output.",
      layoutSpec: {
        kind: "generated",
        name: "workflow-ribbon",
        intent: "Show a left-to-right product workflow",
        requiredSlots: ["title", "step-1", "step-2", "step-3", "step-4"],
        regions: [
          { id: "solution-title", slot: "title", x: 0.08, y: 0.08, width: 0.84, height: 0.14, zIndex: 1 },
          { id: "solution-1", slot: "step-1", x: 0.08, y: 0.36, width: 0.18, height: 0.26, zIndex: 1 },
          { id: "solution-2", slot: "step-2", x: 0.3, y: 0.36, width: 0.18, height: 0.26, zIndex: 1 },
          { id: "solution-3", slot: "step-3", x: 0.52, y: 0.36, width: 0.18, height: 0.26, zIndex: 1 },
          { id: "solution-4", slot: "step-4", x: 0.74, y: 0.36, width: 0.18, height: 0.26, zIndex: 1 },
        ],
        balance: "grid",
      },
      assetRefs: ["knowledge-graph-icon"],
    },
    {
      id: "slide-close",
      role: "closing",
      title: "Make grounded outputs the default team workflow",
      headline: "Start with one high-value knowledge workspace",
      body: ["Choose a team source set", "Define repeatable outputs", "Measure adoption through shared artifacts"],
      visualIntent: "Focused closing callout with next-step checklist.",
      layoutSpec: {
        kind: "locked",
        name: "closing-callout",
        intent: "End with a concise recommendation and checklist",
        requiredSlots: ["title", "headline", "checklist"],
        regions: [
          { id: "close-title", slot: "title", x: 0.1, y: 0.14, width: 0.8, height: 0.16, zIndex: 1 },
          { id: "close-headline", slot: "headline", x: 0.16, y: 0.36, width: 0.68, height: 0.14, zIndex: 1 },
          { id: "close-list", slot: "checklist", x: 0.22, y: 0.56, width: 0.56, height: 0.22, zIndex: 1 },
        ],
        balance: "centered",
      },
      assetRefs: [],
    },
  ],
  qaReport: {
    status: "not_run",
    issues: [],
  },
  renderMetadata: {
    engine: "pptxgenjs-native",
    slideCount: 4,
    editableCompatibility: "native-v1",
    editablePrimitiveCountsBySlide: [],
    warnings: [],
  },
} satisfies PresentationSourceV1;
