import { withBilledModelGateway } from "../../../shared/model-gateway/index";
import { logger } from "../../../shared/logger";
import { buildChatTitlePrompt } from "../agent/prompts";
import { type LlmExecutionConfig } from "../../content/model-gateway-audit";
import type { ContentBillingPort } from "../../content/billing-port";
import { updateThreadTitleIfMatches } from "./repository";
import {
  normalizeChatTitle,
  normalizeGeneratedChatTitle,
  resolveAssistantContent,
} from "./title";

export type GenerateThreadTitleInput = {
  teamId: string;
  workspaceId: string;
  threadId: string;
  traceId?: string;
  userId: string;
  userMessageId: string;
  messageContent: string;
  profileAlias: string;
  modelAlias: string;
  providerModel?: string;
  gatewayConfigId: string;
  llm?: LlmExecutionConfig;
  parentSpanId?: string | null;
  /**
   * Required: this used to be optional, and the worker path never passed it, so
   * every title generated by a background job went unbilled while the in-process
   * path charged for the identical operation.
   */
  billing: ContentBillingPort;
};

/** Applying a title performs no model call, so it needs no billing port. */
export type ApplyGeneratedThreadTitleInput = Omit<
  GenerateThreadTitleInput,
  "billing"
> & {
  billing?: ContentBillingPort;
  expectedTitle: string;
  title: string;
};

export function buildFallbackThreadTitle(messageContent: string) {
  const normalized = messageContent
    .replace(/[`*_#>\[\](){}]/g, " ")
    .replace(/\s+/g, " ")
    .trim();

  return normalizeChatTitle(normalized, "New conversation");
}

export async function generateThreadTitle(input: GenerateThreadTitleInput) {
  const isByok = input.llm?.executionMode === "BYOK";

  const completion = await withBilledModelGateway(
    {
      billing: input.billing,
      gatewayConfigId: input.gatewayConfigId,
      context: {
        teamId: input.teamId,
        workspaceId: input.workspaceId,
        actorUserId: input.userId,
        feature: "chat",
        intent: { mode: "billed" },
        scopeKind: "worker-job",
        scopeId: input.traceId ?? input.userMessageId,
        threadId: input.threadId,
        messageId: input.userMessageId,
      },
    },
    (gateway) =>
      gateway.chat.complete(
        {
          model: isByok
            ? input.llm?.providerModel ?? input.providerModel ?? input.modelAlias
            : input.providerModel ?? input.modelAlias,
          profileAlias: isByok ? undefined : input.profileAlias,
          messages: [
            {
              role: "user",
              content: buildChatTitlePrompt(input.messageContent),
            },
          ],
          executionMode: input.llm?.executionMode,
          providerHint: input.llm?.providerHint,
          byokModelId: input.llm?.byokModelId,
          credentialId: input.llm?.credentialId,
          byok: input.llm?.byok,
        },
        {
          traceId: input.traceId ?? input.userMessageId,
          operation: "chat.title",
          modelKind: "chat",
          gatewayConfigId: input.gatewayConfigId,
          profileAlias: input.profileAlias,
          modelAlias: input.modelAlias,
          llm: input.llm,
          referenceId: `thread:${input.threadId}:title:${input.userMessageId}`,
          // Pinned verbatim: this reference has been metered under this exact
          // key, so deriving a new one would charge it a second time.
          idempotencyKey: `thread-title:${input.userMessageId}`,
        },
      ),
  );

  const title = normalizeGeneratedChatTitle(
    resolveAssistantContent({ raw: completion.raw }),
  );
  logger.debug("Generated automatic thread title candidate", {
    threadId: input.threadId,
    userMessageId: input.userMessageId,
    modelAlias: input.modelAlias,
    hasGeneratedTitle: Boolean(title),
  });
  return title;
}

export async function applyGeneratedThreadTitle(
  input: ApplyGeneratedThreadTitleInput,
) {
  const title = normalizeGeneratedChatTitle(input.title);
  if (!title || title === input.expectedTitle) {
    return null;
  }

  return updateThreadTitleIfMatches({
    threadId: input.threadId,
    teamId: input.teamId,
    workspaceId: input.workspaceId,
    expectedTitles: [input.expectedTitle],
    title,
  });
}
