import { z } from "zod";
import { systemModelReadinessSchema } from "./skill-overviews";

/**
 * AI overviews of MCP servers, the market admin's side (`requireMarketAdmin`).
 * The public read side (`aiOverview`, `aiSummary`, `overviewLocales` and the
 * `locale` query of `/v1/mcp*`) lives in `@sourceweft/market-contracts`.
 */

export const mcpOverviewLocaleSchema = z.enum(["en", "zh-CN", "zh-TW"]);

// One version's overview in one language. Plain text, written by a model from
// third-party content: render it as untrusted text, never as HTML.
export const mcpOverviewContentSchema = z.object({
  // One sentence, for cards.
  summary: z.string(),
  whatItDoes: z.string(),
  whenToUse: z.string(),
  // Runtime, accounts and credentials it needs; "" when none.
  requirements: z.string(),
  // What to know before installing; null when there is nothing.
  cautions: z.string().nullable(),
  // MCP category slugs the model chose (1–3), main purpose first.
  suggestedCategories: z.array(z.string()),
});

// GET /v1/market/admin/mcp/:identifier/overview
export const mcpOverviewAdminEntrySchema = z.object({
  locale: mcpOverviewLocaleSchema,
  overview: mcpOverviewContentSchema,
  model: z.string(),
  hidden: z.boolean(),
  generatedAt: z.string(),
  // The input fingerprint it was written from, and whether that is still the
  // version's (a stale one is regenerated by the scheduler).
  inputSha256: z.string(),
  current: z.boolean(),
});

export const getMcpOverviewAdminResponseSchema = z.object({
  identifier: z.string(),
  serverId: z.string(),
  // The latest published version; null when the server has none.
  versionId: z.string().nullable(),
  version: z.string().nullable(),
  // Whether overviews are written for it: a published, public server's
  // latest published version.
  eligible: z.boolean(),
  readmeStatus: z
    .enum([
      "pending",
      "ok",
      "not_found",
      "too_large",
      "unsupported_host",
      "error",
    ])
    .nullable(),
  // The version's input fingerprint now; null without a usable manifest.
  inputSha256: z.string().nullable(),
  // Why the version gets no overview now (e.g. `readme-pending`,
  // `no-content`); null when it would get one.
  skipReason: z.string().nullable(),
  categoriesSource: z.enum(["auto", "ai", "admin"]),
  analysis: z
    .object({
      status: z.enum(["pending", "running", "ready", "failed", "needs-review"]),
      error: z.string().nullable(),
      force: z.boolean(),
      promptVersion: z.string().nullable(),
      taxonomyVersion: z.string().nullable(),
      classification: z
        .object({
          status: z.enum(["ready", "needs-review"]),
          categories: z.array(
            z.object({ slug: z.string(), evidence: z.string() }),
          ),
          rationale: z.string(),
        })
        .nullable(),
      updatedAt: z.string(),
    })
    .nullable(),
  overviews: z.array(mcpOverviewAdminEntrySchema),
  systemModel: systemModelReadinessSchema,
});

// POST /v1/market/admin/mcp/:identifier/overview/regenerate
export const regenerateMcpOverviewResponseSchema = z.object({
  identifier: z.string(),
  versionId: z.string(),
  // False when overviews are not written for the version.
  queued: z.boolean(),
});

// POST /v1/market/admin/mcp/:identifier/overview/hidden
export const setMcpOverviewHiddenRequestSchema = z.object({
  hidden: z.boolean(),
});

export const setMcpOverviewHiddenResponseSchema = z.object({
  identifier: z.string(),
  versionId: z.string(),
  hidden: z.boolean(),
  // Locales changed.
  updated: z.number().int().nonnegative(),
});

// GET /v1/market/admin/mcp/overview/status
export const mcpOverviewStatusResponseSchema = z.object({
  systemModel: systemModelReadinessSchema,
  // Latest published versions of published, public servers.
  eligible: z.number().int().nonnegative(),
  // Of those, still waiting for their README (not queued until it settles).
  readmePending: z.number().int().nonnegative(),
  withOverview: z.number().int().nonnegative(),
  missing: z.number().int().nonnegative(),
  hidden: z.number().int().nonnegative(),
  // A request is queued or running.
  inProgress: z.number().int().nonnegative(),
  // The last request failed.
  failed: z.number().int().nonnegative(),
});

export type GetMcpOverviewAdminResponse = z.infer<
  typeof getMcpOverviewAdminResponseSchema
>;
export type RegenerateMcpOverviewResponse = z.infer<
  typeof regenerateMcpOverviewResponseSchema
>;
export type SetMcpOverviewHiddenRequest = z.infer<
  typeof setMcpOverviewHiddenRequestSchema
>;
export type SetMcpOverviewHiddenResponse = z.infer<
  typeof setMcpOverviewHiddenResponseSchema
>;
export type McpOverviewStatusResponse = z.infer<
  typeof mcpOverviewStatusResponseSchema
>;
