import type { McpReadmeStatus } from "@sourceweft/market-contracts";
import { logger } from "../../../shared/logger";
import {
  getSystemModelReadiness,
  type SystemModelReadiness,
} from "../../../shared/model-gateway/system-client";
import { loadMcpOverviewSubject, mcpOverviewSkipReason } from "./generate";
import { enqueueMcpOverviewJob } from "./queue";
import {
  countMcpOverviewCoverage,
  findMcpServerOverviewTarget,
  listMcpOverviewRows,
  mcpOverviewRepository,
  setMcpOverviewsHidden,
  type McpOverviewAdminRow,
} from "./repository";

/**
 * The market admin's hands on MCP AI overviews (`requireMarketAdmin`): one
 * server's overview and generation state, regenerate, hide, and the
 * catalog's coverage. Every change is logged with the admin who made it.
 */

/** Names settings and the Provider/model, never the key. */
function systemModelView(readiness: SystemModelReadiness) {
  return {
    enabled: readiness.enabled,
    configured: readiness.configured,
    ready: readiness.ready,
    provider: readiness.provider,
    model: readiness.model,
    problems: readiness.problems,
    reason: readiness.reason,
  };
}

export type McpOverviewAdminState = {
  identifier: string;
  serverId: string;
  // The latest published version; null when the server has none.
  versionId: string | null;
  version: string | null;
  // Whether overviews are written for it: published, public, latest.
  eligible: boolean;
  readmeStatus: McpReadmeStatus | null;
  // The input fingerprint the version has now; an overview written from
  // another one is stale and is regenerated by the scheduler.
  inputSha256: string | null;
  // Why the version would get no overview now; null when it would.
  skipReason: string | null;
  categoriesSource: "auto" | "ai" | "admin";
  analysis: Awaited<ReturnType<typeof mcpOverviewRepository.read>>;
  overviews: Array<McpOverviewAdminRow & { current: boolean }>;
  systemModel: ReturnType<typeof systemModelView>;
};

/**
 * A server's latest version with every overview row it has (hidden ones
 * included) and its generation state. Null when no server has this
 * identifier.
 */
export async function findMcpOverviewAdminState(
  identifier: string,
): Promise<McpOverviewAdminState | null> {
  const target = await findMcpServerOverviewTarget(identifier);
  if (!target) return null;
  const readiness = await getSystemModelReadiness();
  if (!target.versionId) {
    return {
      identifier: target.identifier,
      serverId: target.serverId,
      versionId: null,
      version: null,
      eligible: false,
      readmeStatus: null,
      inputSha256: null,
      skipReason: "not-eligible",
      categoriesSource: target.categoriesSource,
      analysis: null,
      overviews: [],
      systemModel: systemModelView(readiness),
    };
  }
  const [subject, analysis, rows] = await Promise.all([
    loadMcpOverviewSubject(target.versionId),
    mcpOverviewRepository.read(target.versionId),
    listMcpOverviewRows(target.versionId),
  ]);
  const inputSha256 = subject?.input?.inputSha256 ?? null;
  return {
    identifier: target.identifier,
    serverId: target.serverId,
    versionId: target.versionId,
    version: target.version,
    eligible: subject?.eligible ?? false,
    readmeStatus: subject?.readmeStatus ?? null,
    inputSha256,
    skipReason: subject ? mcpOverviewSkipReason(subject) : "missing-version",
    categoriesSource: target.categoriesSource,
    analysis,
    overviews: rows.map((row) => ({
      ...row,
      current: inputSha256 !== null && row.inputSha256 === inputSha256,
    })),
    systemModel: systemModelView(readiness),
  };
}

/**
 * Queues a forced replacement of the latest version's overview; the current
 * one stays live until the new one is published. Null when no server has
 * this identifier or it has no published version; `queued` is false for a
 * version overviews are not written for.
 */
export async function regenerateMcpOverview(input: {
  identifier: string;
  actorUserId: string;
}): Promise<{
  identifier: string;
  versionId: string;
  queued: boolean;
} | null> {
  const target = await findMcpServerOverviewTarget(input.identifier);
  if (!target?.versionId) return null;
  const subject = await loadMcpOverviewSubject(target.versionId);
  let queued = false;
  if (subject?.eligible) {
    // A fresh request id: a finished or failed scheduled job never swallows
    // this one.
    queued = Boolean(
      await enqueueMcpOverviewJob({
        mcpServerVersionId: target.versionId,
        mcpServerId: target.serverId,
        reason: "regenerate",
      }),
    );
  }
  logger.info("MCP overview regenerate requested", {
    actorUserId: input.actorUserId,
    identifier: target.identifier,
    mcpServerVersionId: target.versionId,
    queued,
  });
  return { identifier: target.identifier, versionId: target.versionId, queued };
}

/**
 * Hides or shows every language of the latest version's overview; a hidden
 * overview stays hidden when it is regenerated. Null when there is no such
 * server or no overview to hide.
 */
export async function setMcpOverviewHidden(input: {
  identifier: string;
  hidden: boolean;
  actorUserId: string;
}): Promise<{
  identifier: string;
  versionId: string;
  hidden: boolean;
  updated: number;
} | null> {
  const target = await findMcpServerOverviewTarget(input.identifier);
  if (!target?.versionId) return null;
  const rows = await listMcpOverviewRows(target.versionId);
  if (rows.length === 0) return null;
  const updated = await setMcpOverviewsHidden({
    versionId: target.versionId,
    hidden: input.hidden,
  });
  if (updated > 0) {
    logger.info(input.hidden ? "MCP overview hidden" : "MCP overview shown", {
      actorUserId: input.actorUserId,
      identifier: target.identifier,
      mcpServerVersionId: target.versionId,
      locales: updated,
    });
  }
  return {
    identifier: target.identifier,
    versionId: target.versionId,
    hidden: input.hidden,
    updated,
  };
}

/** Whether the system model can write overviews, and how far they have got. */
export async function getMcpOverviewStatus() {
  const [coverage, readiness] = await Promise.all([
    countMcpOverviewCoverage(),
    getSystemModelReadiness(),
  ]);
  return {
    systemModel: systemModelView(readiness),
    ...coverage,
    missing: Math.max(0, coverage.eligible - coverage.withOverview),
  };
}
